-- Public types and enums for the Things API.

--------------------------------------------------------------------------------
-- GENERAL DATA TYPES USED BY REMOTE INTERFACES
--------------------------------------------------------------------------------

---Error generated by the Things API.
---@class (exact) things.Error
---@field public code string Machine-readable error code.
---@field public message LocalisedString Human-readable error message.

---Unique identifier for a Thing.
---@alias things.Id int64

---Thing identifier consumed by the Things API.
---Either the id of a Thing, or the LuaEntity currently representing it.
---@alias things.ThingIdentification things.Id|LuaEntity

---General statuses of a Thing.
---`void` means the Thing has no entity. Different from `destroyed` in that it will not be garbage collected and may later be re-attached to an entity, e.g. by an undo operation.
---`real` means the Thing has a valid real entity.
---`ghost` means the Thing has a valid ghost entity.
---`destroyed` means the Thing is irrevocably gone. Destroyed things will be garbage-collected and cannot be used for any purpose.
---@alias things.Status "void"|"real"|"ghost"|"destroyed"

---Registration options for a type of Thing.
---@class (exact) things.ThingRegistration
---@field public name string Name of the registered Thing type. This MUST be the same name as the key used to register it, and SHOULD match the prototype name of the corresponding entity.
---@field public intercept_construction? boolean If true, Things will intercept player-driven construction of entities of this type and create Things for them automatically. (default: false)
---@field public virtualize_orientation? Core.OrientationClass If given, the orientation of the Thing will be stored and managed by Things instead of relying on Factorio's built-in entity orientation. This allows for more complex orientation scenarios involving compound entities. The orientation will be promoted to the given orientation class if possible.
---@field public migrate_tags_callback? Core.RemoteCallbackSpec A remote callback to invoke when a Thing is built with unrecognized tags. This allows mods using non-Thing custom blueprint data to migrate to Things. The callback will be invoked as `callback(unrecognized_tags: Tags) -> Tags`, and should return a set of Tags to be applied to the Thing.
---@field public initial_tags_callback? Core.RemoteCallbackSpec A remote callback to invoke when a Thing of this type is created through intercepting a construction event. This allows mods to set initial tags on Things of this type. The callback will be invoked as `callback(entity: LuaEntity) -> tags: Tags|nil`, and should return a set of Tags to be applied to the new Thing.
---@field public custom_events? {[things.EventName]: string} Mapping of Things event names to `CustomEventPrototype` names to raise for this Thing type. If not provided, no custom events will be raised for this Thing type.
---@field public no_garbage_collection? boolean If `true`, Things of this type will not be automatically garbage collected when Things thinks they are unreachable. You must manually destroy these Things when they are no longer needed. (default: false)
---@field public no_destroy_children_on_destroy? boolean If `true`, when a Thing of this type is destroyed, its children will NOT be automatically destroyed. (default: false)
---@field public no_void_children_on_void? boolean If `true`, when a Thing of this type is voided, its children will NOT be automatically voided. (default: false)
---@field public children? {[string]: things.ThingRegistration.Child} Specifications for automatic child creation. Note that child keys will be stringified when serialized, so the use of numeric keys can cause problems if not handled carefully.
---@field public allow_in_cursor? "never" Controls the behavior of entity-pipette and cursor stack for this Thing. If set to "never", Things of this type cannot be picked up into the player's cursor. (default: nil, meaning Things of this type use normal Factorio behavior.)
---@field public custom_blueprint_geometry? Core.CustomEntityGeometry If provided, Things will use this custom geometry data when computing bounding boxes and snapping for blueprint entities of this type.

---@class (exact) things.ThingRegistration.Child
---@field public create? LuaSurface.create_entity_param
---@field public offset? MapPosition Position offset of the child relative to the parent Thing's position
---@field public orientation? Core.Dihedral Orientation of the child relative to the parent Thing's orientation
---@field public lifecycle_type? "real-real"|"void-real"|"ghost-real" Determines lifecycle of child based on parent. `real-real` means child is real regardless of whether parent is ghost or real. `void-real` means child is real if parent is real, void if parent is ghost. `ghost-real` means child is real if parent is real, ghost if parent is ghost. (default: `ghost-real`)

---Registration options for a graph of Things.
---@class (exact) things.GraphRegistration
---@field public name string Name of the registered graph.
---@field public directed? boolean Whether the graph is directed (default: false).
---@field public custom_events? {[things.GraphEventName]: string} Mapping of Things graph event names to `CustomEventPrototype` names to raise for this graph. If not provided, no custom events will be raised for this graph.

---Representation of an edge in a graph of Things.
---@class (exact) things.GraphEdge
---@field public from int64 Edge emanates from this Thing ID. (In undirected graphs, the lower id.)
---@field public to int64 Edge points to this Thing ID. (In undirected graphs, the higher id.)
---@field public data? Tags Optional user data associated with this edge.

---@class (exact) things.NamedGraphEdge: things.GraphEdge
---@field public name string The name of the graph this edge belongs to.

---A set of graph names.
---@alias things.GraphSet {[string]: true}

---Info about a Thing's relationship to its parent.
---[1]: The ID of the parent Thing.
---[2]: The key under which this Thing is registered in its parent's children.
---[3]: The position of this Thing relative to its parent, if any.
---[4]: The orientation of this Thing relative to its parent, if any.
---@alias things.ParentRelationshipInfo [int64, string|int, MapPosition?, Core.Dihedral?]

---A summary of a Thing's children, indexed by child key.
---@alias things.ThingChildrenSummary {[string|int]: things.ThingSummary}

---Serializable summary information about a Thing.
---@class (exact) things.ThingSummary
---@field public id things.Id The id of the Thing.
---@field public name string The name of the Thing's registration.
---@field public entity LuaEntity? The current entity of the Thing, if it has one. This entity is pre-checked for validity at the time the summary is generated.
---@field public status things.Status The current status of the Thing.
---@field public virtual_orientation Core.Orientation? The current virtual orientation of the Thing, if it has one. This will always be nil for Thing types that do not virtualize orientation.
---@field public tags Tags? The current tags of the Thing.
---@field public parent? things.ParentRelationshipInfo Information about this Thing's parent, if any.
---@field public transient_children? {[int|string]: LuaEntity} Map from child indices (which may be numbers or strings) to child entities that are not themselves Things.

---Options controlling how a Thing is created via `create_thing`.
---@class (exact) things.CreateThingParams
---@field public entity LuaEntity The *valid* entity to associate the new Thing with. This entity must not already be associated with an existing Thing.
---@field public name? string If given, the new Thing will be created as an instance of the registered Thing type with this name. If not given, name will be inferred from the entity type.
---@field public tags? Tags Initial tags to set on the created Thing.
---@field public parent? things.ThingIdentification If given, create the new Thing as a child of this Thing.
---@field public child_index? int|string The index of the new Thing within its parent's children, if any. If not given, the new Thing will be added at the end of the parent's children.
---@field public relative_pos? MapPosition The position of the new Thing relative to its parent, if any.
---@field public relative_orientation? Core.Dihedral The orientation of the new Thing relative to its parent, if any.
---@field public devoid? things.ThingIdentification If given, instead of creating a new Thing, devoid the given voided Thing. Cannot be given with `parent`; the new Thing will retain the parent of the voided Thing.

---Entity within a blueprint being extracted.
---@class (exact) things.ExtractedEntity
---@field public index int The index of the entity within the extraction process.
---@field public bp_entity BlueprintEntity The blueprint entity data.
---@field public entity LuaEntity The in-world entity this blueprint entity represents.
---@field public thing_id things.Id? The Thing this blueprint entity represents.
---@field public deleted true? If `true`, this entity was deleted by an atomic blueprint operation.

--------------------------------------------------------------------------------
-- EVENT DATA TYPES
--------------------------------------------------------------------------------

---Thing event names that can be rebroadcasted as Factorio custom events.
---@alias things.EventName "on_initialized"|"on_status"|"on_tags_changed"|"on_orientation_changed"|"on_position_changed"|"on_children_changed"|"on_parent_changed"|"on_child_status"|"on_parent_status"|"on_edge_status"|"on_children_normalized"|"on_immediate_voided"

---Graph event names that can be rebroadcasted as Factorio custom events.
---@alias things.GraphEventName "on_edge_changed"

---Event fired when a Thing with a new ID is generated in the world.
---Does not apply to undo, revival, etc of pre-existing Things.
---@alias things.EventData.on_initialized things.ThingSummary

---Event fired when a Thing's lifecycle status changes.
---@class (exact) things.EventData.on_status
---@field public thing things.ThingSummary Summary of the Thing whose status changed.
---@field public old_status things.Status The previous status of the Thing.
---@field public new_status things.Status The new status of the Thing.

---Event parameters for when Thing tags change. Note that for performance
---reasons, Things does not deep compare tags, so this event may be raised
---in certain cases even when tags haven't meaningfully changed.
---@class (exact) things.EventData.on_tags_changed
---@field public thing things.ThingSummary Summary of the Thing whose tags changed.
---@field public new_tags Tags The new tags of the Thing.
---@field public old_tags Tags The previous tags of the Thing.
---@field public cause "api"|"engine" Source of the tag change event.

---Event raised when the orientation of a Thing changes.
---@class (exact) things.EventData.on_orientation_changed
---@field public thing things.ThingSummary Summary of the Thing whose orientation changed.
---@field public old_orientation? Core.Orientation The previous orientation of the Thing.
---@field public new_orientation Core.Orientation The new orientation of the Thing.

---Event raised when a Thing's position changes.
---@class (exact) things.EventData.on_position_changed
---@field public thing things.ThingSummary Summary of the Thing whose position changed.
---@field public old_position? MapPosition The previous position of the Thing.
---@field public new_position MapPosition The new position of the Thing.

---Event raised when the composition of a Thing's children changes.
---@class (exact) things.EventData.on_children_changed
---@field public thing things.ThingSummary Summary of the Thing whose children changed.
---@field public added things.ThingSummary|nil If a child was added, its summary.
---@field public removed things.ThingSummary[]|nil Summary of the removed children.

---Event raised when a Thing's parent changes.
---@class (exact)things.EventData.on_parent_changed
---@field public thing things.ThingSummary Summary of the Thing whose parent changed.
---@field public new_parent things.ThingSummary|nil Summary of the new parent, if any.

---Event raised when a Thing's child changes status.
---@class (exact) things.EventData.on_child_status
---@field public thing things.ThingSummary Summary of the Thing whose children's status changed.
---@field public child things.ThingSummary Summary of the child whose status changed.
---@field public child_index string|int The key under which the child is registered in the parent.
---@field public old_child_status things.Status The previous status of the child.

---Event raised when a Thing's parent changes status.
---@class (exact) things.EventData.on_parent_status
---@field public thing things.ThingSummary Summary of the Thing whose parent's status changed.
---@field public parent things.ThingSummary Summary of the parent whose status changed.
---@field public old_parent_status things.Status The previous status of the parent.

---Notifies a graph when its edge set changes.
---@class (exact) things.EventData.on_edge_changed
---@field public change "create"|"delete"|"set-data" The type of change that occurred.
---@field public graph_name string The name of the graph whose edges changed.
---@field public edge things.GraphEdge Edge that was changed.
---@field public from things.ThingSummary Summary of the Thing at the from end of the edge.
---@field public to things.ThingSummary Summary of the Thing at the to end of the edge

---Notifies a Thing when another thing connected it by a graph edge changes status.
---@class (exact) things.EventData.on_edge_status
---@field public thing things.ThingSummary Thing opposite the changed thing along the given edge.
---@field public changed_thing things.ThingSummary Thing whose status changed.
---@field public graph_name string The name of the graph where the status changed.
---@field public edge things.GraphEdge Edge whose status changed.
---@field public old_status things.Status The previous status of the opposite Thing.
---@field public new_status things.Status The new status of the opposite Thing.

---Event that takes place after automatically generated children are normalized.
---This means that all automatic children have been created, devoided, or revived
---as necessary to match the current state of the parent Thing.
---@alias things.EventData.on_children_normalized things.ThingSummary

---Event raised inline when a Thing is voided. This event occurs mid-frame and
---you should take care to avoid causing event cancer. The only valid use
---for this event is to collect data about the Thing before its entity is
---destroyed.
---@alias things.EventData.on_immediate_voided things.ThingSummary
